# Generated by Django 5.0 on 2024-01-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(limit_choices_to='title', on_delete=django.db.models.deletion.CASCADE, to='exam.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(limit_choices_to='city__title', on_delete=django.db.models.deletion.CASCADE, to='exam.street'),
        ),
    ]
