# Generated by Django 5.0 on 2024-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_shop_city_alter_shop_open_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_date',
            field=models.TimeField(),
        ),
    ]
